// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs3KUFO0QPHzSECn1OvfhIqXRqBah5Jc0',
    appId: '1:701235302547:web:2774ef6590478e6b117d66',
    messagingSenderId: '701235302547',
    projectId: 'flutter-test-b18b7',
    authDomain: 'flutter-test-b18b7.firebaseapp.com',
    storageBucket: 'flutter-test-b18b7.appspot.com',
    measurementId: 'G-JY8PNPNKKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_yMNyps49GOZOP2GBTviFHXTbE2O0140',
    appId: '1:701235302547:android:a8ab0a86c460e665117d66',
    messagingSenderId: '701235302547',
    projectId: 'flutter-test-b18b7',
    storageBucket: 'flutter-test-b18b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGbvGEfoPR1AHiFj2d-39bZGLjLJ_lFiE',
    appId: '1:701235302547:ios:c04c8f2f63fcf75c117d66',
    messagingSenderId: '701235302547',
    projectId: 'flutter-test-b18b7',
    storageBucket: 'flutter-test-b18b7.appspot.com',
    iosClientId: '701235302547-9v45vi8jhovhkmis97u8s3hrfts578b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
